### ISSUE TITLE
linux无法下载插件

### ISSUE THREAD

**Issue by NealScx** [RShock/nonebot_plugin_ikun_evolution#1]
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
ERROR: Could not find a version that satisfies the requirement nonebot-plugin-ikun-evolution (from versions: none)
ERROR: No matching distribution found for nonebot-plugin-ikun-evolution

**Comment by RShock** [comment]
我觉得是网络不稳定导致的，可以换成从github直接下载后放在插件文件夹内的方法。
